name: Build Unsigned IPA
# Repo: https://github.com/Ihaveadream21/Feather
# Workspace: Feather.xcworkspace

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build archive
        run: |
          xcodebuild \
            -workspace "Feather.xcworkspace" \
            -scheme "Feather" \
            -configuration Release \
            -archivePath build/Feather.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_STYLE="Manual"

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath build/Feather.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/Specifications/ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Unsigned-Feather-IPA
          path: build/ipa/*.ipa
